const sampleDataWomen = {
  products: [
    {
      name: "Floral Summer Dress",
      slug: "floral-summer-dress",
      category: "Women's Dresses",
      description: "Lightweight and breezy dress perfect for summer outings.",
      images: ["/assets/as1/a1.jpg", "/assets/as1/a2.jpg"],
      price: 70,
      originalPrice: 90,
      brand: "Zara",
      rating: 4.6,
      numReviews: 18,
      stock: 12,
      isFeatured: true,
      bannerUrl: "banner-floral.jpg",
      tags: ["Summer", "Elegant"],
      sizes: ["S", "M", "L"],
      colors: ["Red", "Blue", "White"],
      discount: 22,
    },
    {
      name: "White Blouse",
      slug: "white-blouse",
      category: "Tops & Blouses",
      description: "Elegant white blouse with subtle detailing.",
      images: ["/assets/as1/b1.jpg", "/assets/as1/b2.jpg"],
      price: 55,
      originalPrice: 70,
      brand: "H&M",
      rating: 4.4,
      numReviews: 14,
      stock: 15,
      isFeatured: true,
      bannerUrl: null,
      tags: ["Elegant", "Casual"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["White", "Beige"],
      discount: 21,
    },
    {
      name: "Denim Skirt",
      slug: "denim-skirt",
      category: "Women's Skirts",
      description: "Classic denim skirt for casual or semi-formal wear.",
      images: ["/assets/as1/c1.jpg", "/assets/as1/c2.jpg"],
      price: 60,
      originalPrice: 80,
      brand: "Levi's",
      rating: 4.5,
      numReviews: 10,
      stock: 10,
      isFeatured: true,
      bannerUrl: "banner-denim.jpg",
      tags: ["Casual", "Streetwear"],
      sizes: ["S", "M", "L"],
      colors: ["Blue", "Black"],
      discount: 25,
    },
    {
      name: "Red Hoodie",
      slug: "women-red-hoodie",
      category: "Women's Sweatshirts",
      description: "Comfy hoodie perfect for chilly days.",
      images: ["/assets/as1/d1.jpg", "/assets/as1/d2.jpg"],
      price: 65,
      originalPrice: 85,
      brand: "Nike",
      rating: 4.7,
      numReviews: 20,
      stock: 8,
      isFeatured: false,
      bannerUrl: null,
      tags: ["Leisure", "Sport"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Black"],
      discount: 23,
    },
    {
      name: "Black Leather Jacket",
      slug: "women-black-leather-jacket",
      category: "Jackets",
      description: "Stylish leather jacket for a bold look.",
      images: ["/assets/as1/e1.jpg", "/assets/as1/e2.jpg"],
      price: 220,
      originalPrice: 250,
      brand: "Guess",
      rating: 4.8,
      numReviews: 12,
      stock: 5,
      isFeatured: true,
      bannerUrl: null,
      tags: ["Elegant", "Streetwear"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black"],
      discount: 12,
    },
    {
      name: "Striped Blouse",
      slug: "striped-blouse",
      category: "Tops & Blouses",
      description: "Chic striped blouse suitable for work and casual outings.",
      images: ["/assets/as1/f1.jpg", "/assets/as1/f2.jpg"],
      price: 50,
      originalPrice: 65,
      brand: "Mango",
      rating: 4.3,
      numReviews: 8,
      stock: 10,
      isFeatured: false,
      bannerUrl: null,
      tags: ["Elegant", "Casual"],
      sizes: ["S", "M", "L"],
      colors: ["White", "Blue"],
      discount: 23,
    },
    {
      name: "Pleated Midi Skirt",
      slug: "pleated-midi-skirt",
      category: "Women's Skirts",
      description: "Flowy midi skirt with elegant pleats.",
      images: ["/assets/as1/g1.jpg", "/assets/as1/g2.jpg"],
      price: 75,
      originalPrice: 95,
      brand: "Zara",
      rating: 4.7,
      numReviews: 11,
      stock: 6,
      isFeatured: true,
      bannerUrl: null,
      tags: ["Elegant", "Summer"],
      sizes: ["S", "M", "L"],
      colors: ["Pink", "Beige", "White"],
      discount: 21,
    },
    {
      name: "Casual Sneakers",
      slug: "women-casual-sneakers",
      category: "Shoes",
      description: "Comfortable sneakers for everyday wear.",
      images: ["/assets/as1/h1.jpg", "/assets/as1/h2.jpg"],
      price: 80,
      originalPrice: 100,
      brand: "Nike",
      rating: 4.5,
      numReviews: 22,
      stock: 14,
      isFeatured: true,
      bannerUrl: null,
      tags: ["Sport", "Casual"],
      sizes: ["6", "7", "8", "9"],
      colors: ["White", "Pink", "Black"],
      discount: 20,
    },
    {
      name: "Beige Summer Hat",
      slug: "beige-summer-hat",
      category: "Accessories",
      description: "Light hat to protect you from the sun in style.",
      images: ["/assets/as1/i1.jpg"],
      price: 35,
      originalPrice: 45,
      brand: "H&M",
      rating: 4.2,
      numReviews: 5,
      stock: 20,
      isFeatured: false,
      bannerUrl: null,
      tags: ["Casual", "Summer"],
      sizes: ["One Size"],
      colors: ["Beige", "White"],
      discount: 22,
    },
    {
      name: "Leather Boots",
      slug: "women-leather-boots",
      category: "Shoes",
      description: "Durable and stylish leather boots.",
      images: ["/assets/as1/j1.jpg", "/assets/as1/j2.jpg"],
      price: 150,
      originalPrice: 180,
      brand: "Dr. Martens",
      rating: 4.9,
      numReviews: 35,
      stock: 4,
      isFeatured: true,
      bannerUrl: null,
      tags: ["Elegant", "Streetwear"],
      sizes: ["36", "37", "38", "39", "40"],
      colors: ["Brown", "Black"],
      discount: 17,
    },
    {
      name: "Grey Sweatpants",
      slug: "women-grey-sweatpants",
      category: "Women's Sweatpants",
      description: "Comfortable sweatpants for casual wear.",
      images: ["/assets/as1/k1.jpg", "/assets/as1/k2.jpg"],
      price: 45,
      originalPrice: 60,
      brand: "Puma",
      rating: 4.1,
      numReviews: 9,
      stock: 18,
      isFeatured: false,
      bannerUrl: null,
      tags: ["Leisure", "Sport"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Grey", "Black"],
      discount: 25,
    },
    {
      name: "Brown Leather Belt",
      slug: "women-brown-leather-belt",
      category: "Accessories",
      description: "Classic belt to complete your outfit.",
      images: ["/assets/as1/l1.jpg", "/assets/as1/l2.jpg"],
      price: 40,
      originalPrice: 50,
      brand: "Gucci",
      rating: 4.7,
      numReviews: 12,
      stock: 10,
      isFeatured: false,
      bannerUrl: null,
      tags: ["Elegant", "Casual"],
      sizes: ["M", "L", "XL"],
      colors: ["Brown", "Black"],
      discount: 20,
    },
  ],
};

export default sampleDataWomen;
